 <?PHP 
mk:@MSITStore:C:\Program%20Files%20(x86)\Image-Line\FL%20Studio%2012\Help\FD.chm::/web/documents/ProductInfo.html
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Product Info</title>
<link type="text/css" href="../documents/textstyles_nf.css" rel="stylesheet">
<link type="text/css" href="../documents/print.css" rel="stylesheet"  media="print">
<meta name="generator" content="EZGenerator 4.3.5.8 (intern-fl_help[2])">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="description" content="">
<meta name="keywords" content="">
<meta http-equiv="last-modified" content="Mon, 24 10 2016 10:17:19 GMT">
<script type="text/javascript" src="../jquery.js"></script>
<script type="text/javascript" src="../jquery_utils.js"></script>

<!--scripts-->
<style type="text/css">
.col3 .div_col{margin-right:3px;}
.headDiv{position:relative;border-radius: 6px;overflow:auto;margin:5px;}
.bpr_1{background: #ff5e00;box-shadow: 1px 1px 2px rgba(0,0,0,0.17);border-radius: 4px;padding:6px;margin: 0px 5px 0px 0px;}a.bpr_1,a.bpr_1:visited,input.bpr_1,button.bpr_1{font: bold 14px Verdana, Geneva, Arial, Helvetica, sans-serif;color:#FFFFFF;text-decoration:none;}.bpr_1.hover,.bpr_1:hover{background: #FFFFFF;}a.bpr_1:hover,input.bpr_1:hover,button.bpr_1:hover{color:#949494;}.col3{position:relative;border-radius: 2px;overflow:auto;}
.block{border-radius: 2px;overflow:auto;margin:5px;background: #39444e;}
</style>

 <script>
$.getJSON( "http://www.image-line.com/flstudio-feature-comparison/cors.php", function( data ) {
document.location="http://www.image-line.com/flstudio-feature-comparison/"
});
</script>
<!--menu_java-->
<!--/menu_java-->
<!--endscripts-->
</head>
<body>
<div id="container">
	<div id="topbar">
      <ul id="mmenu"><!--mmenu--><li id="ci23"><a id="ma" class="mmenu active" href="../documents/productinfo.html" target="_self">FL STUDIO</a></li>
<li id="ci29"><a class="mmenu" href="../documents/toolsandapplications.html" target="_self">PLUGINS, MOBILE & CONTENT</a></li>
<!--/mmenu--></ul>
    </div>
    <div id="xm1">
		<div align="left" id="xm2" rel="23">
			<!--page--><div class="pageheader"><h1>FL STUDIO EDITIONS</h1></div><!--pheader--><div class="rvps0"><b> </b></div>
<br>
<div class="rvps1">	<div id="div_1" class="headDiv">
		<div class="div_col dc_0" style="overflow:auto; background: #18242D; width:173px;" >
			<div style="padding:15px;"><div class="rvps1"><span class="rvts80"><b>?</b></span></div>
</div>
		</div>
		<div class="div_col dc_1" style="overflow:auto; background: #18242d;" >
			<div style="padding:15px;"><div class="rvps3"><b>Amazing fact:</b> the FL Studio demo is downloaded over <b>30,000</b> times each day!<b> </b>When you're done testing, <b>FL Studio</b> is available in several editions, as shown below. </div>
<div class="rvps3"><br></div>
<br>
<div class="rvps0"><span class="rvts64"><b>Please check the FEATURES &amp; PLUGINS you want are included in the version you buy!</b></span></div>
</div>
		</div>
	</div>
</div>
<br>
<div class="rvps1"><a href="http://www.image-line.com/flstudio/" target="_blank" class="css_button bpr_1">Buy FL Studio</a></div>
<br>
<div class="rvps1">	<div id="div_2" class="col3">
		<div class="div_col dc_0" style="overflow:hidden;border-right: 6px solid #28343d; background: #39444e; width:30%;" >
			<div style="padding:10px;"><div class="rvps1"><img style="width:259px;height:88px;" alt="" title="Editions FL12_signature" src="Editions_FL12_signature.png"></div>
<br>
<div class="rvps1">Download version: <span class="cfont" style="font-weight:bold;font-size:14px;color:#ff7629;" data-size="14">299 USD</span></div>
<div class="rvps1">Boxed version: <span class="cfont" style="font-weight:bold;font-size:14px;color:#ff7629;" data-size="14">399 USD</span></div>
<br>
<div class="rvps0"><b>Includes:</b></div>
<br>
<ul class="ul_0_0">
<li class="li_0_0"><i>All FL Producer Edition features +</i></li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/plugins/Synths/Harmless/"  title="Harmless" target="_top">Harmless</a> synth</li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/plugins/Tools/NewTone/"  title="NewTone" target="_top">Newtone</a> pitch/time editor</li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/plugins/Effects/Gross+Beat/"  title="Gross Beat" target="_top">Gross Beat</a> effect</li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/plugins/Effects/Pitcher/"  title="Pitcher" target="_top">Pitcher</a> effect</li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/documents/directwave.html"  title="DirectWave Sampler / ROMpler" target="_blank">DirectWave</a> full sampler</li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/documents/hardcore.html"  title="Hardcore Guitar FX Suite" target="_blank">Hardcore</a> guitar effects suite </li>
<li class="li_0_0">FL <a class="rvts4" href="http://www.image-line.com/documents/video_player.html"  title="See more at Image-Line" target="_blank">Video player</a></li>
<li class="li_0_0"><b>Lifetime FREE updates</b> to FL Studio Producer Edition &amp; plugins listed above by download. </li>
<li class="li_0_0"><span class="rvts64">NOT all plugins (</span><a class="rvts4" href="http://support.image-line.com/redirect/flstudio_editions_compared"  title="Please check the plugins you get here!" target="_blank">Check here</a><span class="rvts64">)</span></li>
</ul>
<br>
<div class="rvps0"><b>Want more? </b></div>
<br>
<div class="rvps3"><span class="rvts8">Grab the </span><a class="rvts12" href="https://support.image-line.com/jshop/shop.php"  title="ALL Plugins Bundle" target="_blank">FL Studio </a><a class="rvts12" href="https://support.image-line.com/jshop/shop.php"  title="ALL Plugins Bundle" target="_blank"><i>All Plugins Bundle</i></a><span class="rvts8"> and save around 65% off the combined price.</span></div>
<br>
<div class="rvps3"><span class="rvts8"><b>Note:</b></span><span class="rvts8"> The </span><span class="rvts8"><i>Signature Bundle</i></span><span class="rvts8"> is a bundle of </span><span class="rvts8"><i>FL Studio Producer Edition </i></span><span class="rvts8">and additional plugins shown above. </span><span class="rvts8"><i>All Plugins Bundle</i></span><span class="rvts8"> is </span><span class="rvts8"><i>FL Studio Producer plus all plugins</i></span><span class="rvts8">.</span></div>
</div>
		</div>
		<div class="div_col dc_1" style="overflow:hidden;border-right: 6px solid #28343d; background: #39444e; width:30%;" >
			<div style="padding:10px;"><div class="rvps0"><img style="width:259px;height:88px;" alt="" title="Editions FL12_signature" src="Editions_FL12_producer_1.png"></div>
<br>
<div class="rvps1">Download version: <span class="cfont" style="font-weight:bold;font-size:14px;color:#ff7629;" data-size="14">199 USD </span></div>
<div class="rvps1">Boxed version: <span class="cfont" style="font-weight:bold;font-size:14px;color:#ff7629;" data-size="14">269 USD</span></div>
<br>
<div class="rvps0"><b>Includes:</b></div>
<br>
<ul class="ul_0_0">
<li class="li_0_0"><i>All FL Studio Fruity features + </i></li>
<li class="li_0_0">Multi-track audio recording.</li>
<li class="li_0_0">Audio Clips. </li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/documents/sytrus.html"  title="Sytrus Synthesizer Plugin" target="_blank">Sytrus </a>synthesizer</li>
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/documents/maximus.html"  title="Maximus Compressor/Limiter/Maximizer" target="_blank">Maximus</a> multiband maximizer </li>
<li class="li_0_0">FL <a class="rvts4" href="http://www.image-line.com/documents/edison.html"  title="Edison Wave Editor / Recorder" target="_blank">Edison</a> editor &amp; recorder </li>
<li class="li_0_0">FL <a class="rvts4" href="http://www.image-line.com/documents/slicex.html"  title="Slicex Sample Slicing / Maniupulation Plugin" target="_blank">Slicex</a> loop slicer/arranger</li>
<li class="li_0_0">FL <a class="rvts4" href="http://www.image-line.com/documents/vocodex.html"  title="Vocodex Vocoder" target="_blank">Vocodex</a> vocoder</li>
<li class="li_0_0">FL SynthMaker </li>
<li class="li_0_0"><b>Lifetime FREE updates</b> to Producer Edition by download</li>
<li class="li_0_0"><span class="rvts64">NOT all plugins (</span><a class="rvts4" href="http://support.image-line.com/redirect/flstudio_editions_compared"  title="Please check the plugins you get here!" target="_blank">Check here</a><span class="rvts64">)</span></li>
</ul>
</div>
		</div>
		<div class="div_col dc_2" style="overflow:hidden; background: #39444e; width:30%;" >
			<div style="padding:10px;"><div class="rvps1"><img style="width:259px;height:88px;" alt="" title="Editions FL12_signature" src="Editions_FL12__fruity.png"></div>
<br>
<div class="rvps1">Download version: <span class="cfont" style="font-weight:bold;font-size:14px;color:#ff7629;" data-size="14">99 USD</span></div>
<div class="rvps1">Boxed version: <span class="cfont" style="font-weight:bold;font-size:14px;color:#ff7629;" data-size="14">139 USD</span></div>
<br>
<div class="rvps0"><b>Includes:</b></div>
<br>
<ul class="ul_0_0">
<li class="li_0_0"><a class="rvts4" href="http://www.image-line.com/documents/features.html"  title="Ckeck the table here to see the included instruments and FX" target="_blank"><i>These instruments &amp; effects</i></a></li>
<li class="li_0_0">Mixer (100+ tracks) </li>
<li class="li_0_0">External MIDI control</li>
<li class="li_0_0">Unlimited instrument Channels</li>
<li class="li_0_0">Step Sequencer </li>
<li class="li_0_0">FL <a class="rvts4" href="http://www.image-line.com/documents/directwave.html"  title="DirectWave Sampler / ROMpler" target="_blank">Direct Wave</a> (player)</li>
<li class="li_0_0">Supports VST/2/3 &amp; DX </li>
<li class="li_0_0">Supports WAV, MP3, OGG </li>
<li class="li_0_0">MIDI import/export</li>
<li class="li_0_0">Playlist arranging </li>
<li class="li_0_0">Piano typing keyboard</li>
<li class="li_0_0">Automation Clips &amp; Editing</li>
<li class="li_0_0">Pattern Clips</li>
<li class="li_0_0">Piano roll with chords &amp; slides </li>
<li class="li_0_0">Automation record &amp; edit </li>
<li class="li_0_0">ASIO support (for low latency) </li>
<li class="li_0_0">Internal controllers </li>
<li class="li_0_0">Use as a VSTi instrument</li>
<li class="li_0_0"><b>Lifetime FREE updates</b> </li>
<li class="li_0_0"><span class="rvts64">NO audio recording.</span></li>
<li class="li_0_0"><span class="rvts64">NO Audio Clips.</span></li>
<li class="li_0_0"><span class="rvts64">NOT all plugins (</span><a class="rvts4" href="http://support.image-line.com/redirect/flstudio_editions_compared"  title="Please check the plugins you get here!" target="_blank">Check here</a><span class="rvts64">)</span></li>
</ul>
<br>
</div>
		</div>
	</div>
</div>
<br>
<br>
<div class="rvps1"><b>See the</b><a class="rvts4" href="http://support.image-line.com/redirect/flstudio_editions_compared"  title="FL Studio feature comparison table online." target="_blank"><b> FL Studio editions feature comparison table</b></a> &nbsp;<b>or</b> &nbsp;<a class="rvts4" href="http://support.image-line.com/redirect/FLEditions"  title="FL Studio Editions discussed online." target="_blank"><b>FL Studio editions discussed.</b></a></div>
<br>
<div class="rvps0"><span class="rvts16"><b>Why buy FL Studio?</b></span></div>
<br>
<div class="rvps0">When <a class="rvts4" href="http://support.image-line.com/redirect/installflstudio"  title="See a video on how to download, install & register FL Studio" target="_blank">register</a> your purchase, you will receive:</div>
<div class="rvps0">&nbsp;</div>
<ul class="ul_0_0">
<li class="li_0_0"><b>Lifetime FREE Updates</b> to the edition you buy via download. That's every future version of FL Studio free!</li>
<li class="li_0_0">Unlimited technical <a class="rvts4" href="http://support.image-line.com" target="_blank">support</a>. </li>
<li class="li_0_0">Participation in the <a class="rvts4" href="http://forum.image-line.com/index.php"  title="Image Line Forums" target="_blank">online user community</a>. </li>
<li class="li_0_0">Free <a class="rvts4" href="http://support.image-line.com/redirect/user_content"  title="Download samples, presets and other content" target="_top">downloads, content</a> and <a class="rvts4" href="http://www.image-line.com/documents/samplefusion.html" target="_blank">samples</a>. </li>
<li class="li_0_0">Access to pre-release betas of <a class="rvts4" href="http://forum.image-line.com/viewforum.php?f=1947"  title="FL Studio Beta Testing" target="_blank">FL Studio</a> and <a class="rvts4" href="http://forum.image-line.com/viewforum.php?f=1919"  title="Plugin / Component Beta Testing" target="_blank">plugins</a>.</li>
<li class="li_0_0">Install and unlock FL Studio on any computer with internet access.</li>
<li class="li_0_0">Re-open projects saved while using the FL Studio demo. Don't delete those demo projects!</li>
<li class="li_0_0">Already using the demo? There's nothing more to download, unlock FL Studio from the About panel with your account login.</li>
<li class="li_0_0">By purchasing FL Studio you support us, so that FL Studio and Lifetime Free Updates continues.</li>
</ul>
<br>
<div class="rvps1"><a href="http://www.image-line.com/flstudio/" target="_blank" class="css_button bpr_1"> Buy FL Studio</a></div>
<br>
<div class="rvps1">	<div id="div_3" class="block">
		<div class="div_header">FL STUDIO MOBILE</div>
		<div style="padding:15px;">
<div class="rvps3"><a href="http://www.image-line.com/documents/flstudiomobile.html" target="_blank"><img style="margin: 5px 10px 0px 0px;border: 1px dotted #000000;float:left;" alt="" title="Get FL Studio mobile" src="Register_FLMobile_5.png"></a><b>FL Studio mobile</b> allows you to create complete multi-track music projects on your <b>Android, Apple iOS devices, Windows Phone</b> and <b>Windows App</b>. Then, if you want, load mobile projects into <a class="rvts4" href="../documents/productinfo.html">FL Studio</a> and take them to the next level. If it’s a beat on the Stepsequencer, a melody on the Piano roll or a full song on the Playlist, FL Studio mobile has you covered. Never lose that idea again. </div>
<div class="rvps3"><br></div>
<div class="rvps3">Get it down and happening wherever you are. <a class="rvts4" href="http://www.image-line.com/documents/flstudiomobile.html"  title="Learn more at Image-Line.com" target="_blank">Learn more about FL Studio Mobile</a> - available on Google Play and Apple iTunes stores.</div>
</div>	</div>
</div>
<br>
<div class="rvps3"><span class="rvts8"><b>Notes: 1. </b></span><span class="rvts8">You can upgrade from one FL Studio version to another although it's most cost effective to buy the version you will ultimately use, check the </span><a class="rvts12" href="http://shop.flstudio.com/" target="_blank">shop</a><span class="rvts8"> for pricing details. </span><span class="rvts8"><b>2. </b></span><span class="rvts8">FL preceding a plugin instrument/effect notes it's a 'native' FL Studio version (VST versions that can be used outside FL Studio are usually sold separately). </span><span class="rvts8"><b>3.</b></span><span class="rvts8"> Image-Line reserves the right to change the plugins included with any FL Studio Edition or Bundle. Changes will not apply retrospectively, plugins licensed to you as part of the original bundle will remain yours.</span></div>
<div class="rvps3"><br></div>
<br>
<!--footer--><div class="rvps1"> </div>
<div style="text-align:center"><table style="margin:0 auto;width:100%;" id="table_1f">
<tr><td style="width:100%; vertical-align:bottom;"><div class="rvps1">This page was created with <a class="rvts4" href="http://www.ezgenerator.com" target="_blank">EZGenerator</a> Copyright©<b> </b>2003-2015, Image<b>-</b>Line Software </div>
</td></tr></table>
</div>
<div class="rvps1"><b> &nbsp; &nbsp; &nbsp;</b></div><!--/footer--><!--/page-->
		</div>
  </div>
  <div id="footer">
  </div>
</div>
</body></html> -->
